### ISSUE TITLE
Dev error fixes

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#102]
Edit: collecting a series of TODOs here as a result of this thread

-  [x] add tests for project_config pipeline_arguments sections: pipelines with no project_config options
-  [x] add tests for project_config pipeline_arguments sections: null (flag-like) options
-  [x] add tests for project_config pipeline_arguments sections: basic options with arguments
-  [x]  revert failure messages to failure-level reports rather than sample-level reports

Original message:
 @vreuter Not sure if I'm doing something wrong but the current dev version is passing tests but fails on a real run:
```
looper run pconfig.yaml -d
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 9, in <module>
    load_entry_point('looper==0.6.0.dev0', 'console_scripts', 'looper')()
  File "/share/apps/python/2.7.6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/share/apps/python/2.7.6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/share/apps/python/2.7.6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/share/apps/python/2.7.6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 29, in <module>
    from looper.models import \
ImportError: No module named models
```
is it working for you?

**Comment by nsheff** [comment]
I moved a few things around and progress to this:

```
Command: run (Looper version: 0.6.0-dev)
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 9, in <module>
    load_entry_point('looper==0.6.0.dev0', 'console_scripts', 'looper')()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 749, in main
    looperenv_file=getattr(args, 'env', None))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/loodels.py", line 41, in __init__
    config_file, default_compute, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'looperenv_file'
```

it appears for me the looper-specific Project is broken?

**Comment by vreuter** [comment]
Ah yeah I guess we could keep looperenv_file as the name for the looper version, but it's now renamed more genetically. While I don't think it's a good idea to change the signature to the parameter names, if you prefer we do that in this case, I'm alright with it.

**Comment by vreuter** [comment]
This underscores some value in having a few cases run through the looper CLI API within the suite though

**Comment by nsheff** [comment]
genetically or generically? What have you been reading lately :stuck_out_tongue: ?

I wasn't suggesting anything in particular, just trying to understand it and make it work...

**Comment by nsheff** [comment]
A new error with this update:

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 9, in <module>
    load_entry_point('looper==0.6.0.dev0', 'console_scripts', 'looper')()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 772, in main
    run(prj, args, remaining_args, interface_manager=interface_manager)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 315, in run
    argstring += prj.get_arg_string(pl_id)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 774, in get_arg_string
    default_argtext = create_argtext("default")
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 770, in create_argtext
    optargs_texts = map(make_optarg_text, optargs.items())
TypeError: make_optarg_text() takes exactly 2 arguments (1 given)
```

you're calling the function with incorrect number of args...

**Comment by nsheff** [comment]
This is happening for flag-like options that have no argument. so it's only passing 1 (or rather ['-arg', None]) and confusing the function.

**Comment by nsheff** [comment]
Actually turns out there's a few different issues here, so I think we need some new test cases. I think this should fix it but we need some tests for:
- pipelines with no project_config options
- null (flag-like) options

**Comment by nsheff** [comment]
Next is a logger error:
```
Logged from file looper.py, line 373
Traceback (most recent call last):
  File "/share/apps/python/2.7.6/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/share/apps/python/2.7.6/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/share/apps/python/2.7.6/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/share/apps/python/2.7.6/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```
Not sure what's going on here, but there's now some problem with the way failures are reported.

**Comment by nsheff** [comment]
Ok I fixed it, but this is now backwards to the way it used to be (and should be) isn't it? It shouldn't show errors sample-wise, but error-wise, with a list of samples. I'm pretty sure that's what it used to do. Now it's showing just a list of failed samples and why. It's also doubling some error messages.

**Comment by nsheff** [comment]
This would be prevented by #38 if we get around to that.

**Comment by nsheff** [comment]
BTW `toggle` is actually still not functional. adding this to the checklist...

**Comment by vreuter** [comment]
https://github.com/epigen/looper/pull/106 addresses the first four of the tasks here (tests regarding `pipeline_args` and the reversion of the skip reason reporting strategy).
