### ISSUE TITLE
AttributeDict objects cannot be unpickled

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#108]
I'm having an issue unpickling `AttributeDict` objects.
See reproducible example (same in 0.5 and 0.6dev):

```python
>>> from looper.models import AttributeDict
>>> import pickle
>>> ad = AttributeDict({'a': 1})
>>> pickle.dump(ad, open("ad.pickle", 'wb'))
>>> pickle.load(open("ad.pickle", 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/python/2.7.12/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/cm/shared/apps/python/2.7.12/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/cm/shared/apps/python/2.7.12/lib/python2.7/pickle.py", line 1221, in load_build
    setstate = getattr(inst, "__setstate__", None)
  File "/home/arendeiro/.local/lib/python2.7/site-packages/looper/models.py", line 200, in __getattr__
    if self.__dict__["_attribute_identity"]:
KeyError: '_attribute_identity'
```
This seems to stem from the overwriting of the `__getattr__` method in AttributeDict which assumes an instance will always have a "_attribute_identity" attribute which maybe is not the case when the object is being de-serialized by the pickle module.

**Comment by vreuter** [comment]
Indeed, thanks for catching this @afrendeiro ; I'll work around this.

**Comment by nsheff** [comment]
Related to #79 I think. Probably time to solve this.
