### ISSUE TITLE
__str__ method of Project falls in recursive loop

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#111]
In the overwrite of the [__str__ method of Project](https://github.com/epigen/looper/blob/dev/looper/models.py#L404), when failing to retrieve the `name` attribute of a Project (because it is not set), a string will be formated with the class' name (Project) and the object itself. However the `str`.format method acts on objects by their __str__ method, which raises a `RuntimeError` due to recursion:

```python
>>> from looper.models import Project
>>> prj = Project(
    "metadata/config.yaml",
    default_compute="/home/arendeiro/workspace/looperenv/cemm.yaml")
>>> prj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arendeiro/.local/lib/python2.7/site-packages/looper/models.py", line 296, in __repr__
    return repr(self.__dict__)
  File "/home/arendeiro/.local/lib/python2.7/site-packages/looper/models.py", line 988, in __repr__
    (self.prj, len(self.df))
...
  File "/home/arendeiro/.local/lib/python2.7/site-packages/looper/models.py", line 423, in __str__
    self.__class__.__name__, name=name, data=self)
  File "/home/arendeiro/.local/lib/python2.7/site-packages/looper/models.py", line 423, in __str__
    self.__class__.__name__, name=name, data=self)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

This is easy to miss if you always assign your objects to variables and so on, but when using looper in an interactive session, just by asking the console to return the object it self will cause the error already - maybe something to consider in the tests too.

**Comment by afrendeiro** [comment]
Came across this when looking into #108
