### ISSUE TITLE
pipeline installs fail on microtest

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#15]
When trying to run microtest, if I do not install `open_pipelines` (which I believe is not necessary, right?), I get this error:

```

Successfully imported modules: open_pipelines
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 9, in <module>
    load_entry_point('looper==0.4', 'console_scripts', 'looper')()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 578, in main
    prj.add_sample_sheet()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 381, in add_sample_sheet
    self.sheet.make_samples()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 541, in make_samples
    self.samples.append(self.make_sample(self.df.ix[i].dropna()))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 522, in make_sample
    for _, module in inspect.getmembers(sys.modules[name], lambda member: inspect.ismodule(member)):
KeyError: 'open_pipelines'
```

I believe it is requiring it to be installed, but it is not on my system.

**Comment by afrendeiro** [comment]
The issue was that I allowed the user to point to any folder as that being the one containing the pipelines and then was using that name as the module to go through looking for objects that extend `Sample` - [here](https://github.com/epigen/looper/blob/6b23c8565190242a19f2b2f131b13027d35fafd0/looper/models.py#L514).
I just didn't realize that regardless of where the folder is and is named (which is still important because I need to add it to the PATH), the module to be searched for is allways named `pipelines`, which in my case was never an issue because that is both the name of the module and the directory.

**Comment by nsheff** [comment]
Yes, I see... that can be a problem...
