### ISSUE TITLE
no data sources error?

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#179]
If you give a config file with no data_sources section, you get:

```    raise ValueError("No data sources")
ValueError: No data sources
```

but someone may have a file that doesn't use data sources. this shouldn't be an error, I think.

**Comment by vreuter** [comment]
What do you mean by "a _file_ that doesn't use data sources?"

**Comment by nsheff** [comment]
project_config file with no data_sources section.

**Comment by vreuter** [comment]
Can you try 9c569bfb1d982b1e6887f269d4f54fc7486d4e6b

**Comment by nsheff** [comment]
I'm still getting 
```
Traceback (most recent call last):
  File "/sfs/nfs/blue/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.7.0.dev0', 'console_scripts', 'looper')()
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 956, in main
    compute_env_file=getattr(args, 'env', None))
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/loodels.py", line 29, in __init__
    no_compute_exception=RuntimeError, **kwargs)
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 800, in __init__
    self._set_basic_samples()
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 1245, in _set_basic_samples
    self._samples = self._merge_samples()
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 1266, in _merge_samples
    self.data_sources, self.derived_columns)
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 309, in merge_sample
    extra_vars=row_dict)
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 1915, in locate_data_source
    raise ValueError("No data sources")
ValueError: No data sources
```

**Comment by nsheff** [comment]
Yeah that worked. I like how there was a comment in the code left right there, wondering if this would come up.

**Comment by vreuter** [comment]
Haha yeah that brought a smile for me, too.
