### ISSUE TITLE
summarize broken on dev.

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#192]
```
## [14 of 14] Sample-name (protocol)
No figures file '...figures.tsv'
Traceback (most recent call last):
  File "/sfs/nfs/blue/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.7.0.dev0', 'console_scripts', 'looper')()
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 799, in main
    Summarizer(prj)()
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 575, in __call__
    if self.prj.subproject:
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 437, in __getattr__
    return getattr(self.prj, item)
  File "/sfs/nfs/blue/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 546, in __getattr__
    raise AttributeError(item)
AttributeError: subproject
```

**Comment by vreuter** [comment]
Going ahead and closing per your commit @nsheff
