### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by johanneskoester** [epigen/looper#89]
@nsheff I tried to test looper (the project config part today), but I cannot install it:
```
pip install git+https://github.com/epigen/looper.git
Collecting git+https://github.com/epigen/looper.git
  Cloning https://github.com/epigen/looper.git to /tmp/pip-8o0z6uq1-build
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/looper.egg-info
    writing requirements to pip-egg-info/looper.egg-info/requires.txt
    writing top-level names to pip-egg-info/looper.egg-info/top_level.txt
    writing entry points to pip-egg-info/looper.egg-info/entry_points.txt
    writing pip-egg-info/looper.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/looper.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/looper.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-8o0z6uq1-build/setup.py", line 66, in <module>
        **extra
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/egg_info.py", line 195, in run
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/egg_info.py", line 222, in find_sources
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/egg_info.py", line 306, in run
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/egg_info.py", line 335, in add_defaults
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/command/sdist.py", line 178, in add_defaults
      File "/home/johannes/.local/opt/miniconda/envs/looper-test/lib/python3.5/distutils/dist.py", line 995, in has_scripts
        return self.scripts and len(self.scripts) > 0
    TypeError: object of type 'filter' has no len()
```

I saw that your CI tests run on Python 2. Is looper Python 2 only?

**Comment by nsheff** [comment]
Yes, we have only developed looper on python 2.

**Comment by johanneskoester** [comment]
I suggest to port it to Python 3. Using `__future__`  you can maintain the same code for both. If that does not work with looper, you might at least consider to port the project/sample config part once it has been separated. Otherwise, it will not work together with Snakemake, which is Python 3 only. Python 3 is almost 10 years old now, and all major packages have been ported, so there should be no issues.

**Comment by nsheff** [comment]
I don’t think it should be too hard to port to python3; I believe we have been using mostly 3-compatible features. Last time I checked there was still a bunch of stuff missing in 3, but maybe now is finally the time to change. I'm reluctant to abandon 2 because for many users 2 is still the default on clusters, etc, and supporting only 3 creates an additional barrier to entry. But it probably would not be hard to accommodate both. Comments @vreuter or @afrendeiro ?

**Comment by nsheff** [comment]
Incidentally this particular error is coming from this LOC: https://github.com/epigen/looper/blob/b0619cdc819a0c5094bd7b48ff07ec5cce4cf677/setup.py#L33

`filter` returns a list in python 2 but a `filter` object (which is iterable but has no `len` method) in python 3.
This can be solved like:
```
[i for i in filter(a_function, a_sequence)]
```
which is 2 and 3 compatible. I suppose we just have to identify any such areas; shouldn't be too hard. see [here](http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#filter)

**Comment by vreuter** [comment]
A couple months ago I would've just said let's scrap support for 2 whenever we release a 1.0 version, but I've been mostly won over to the desire to continue to support 2.7. But yes, I totally think we should support 3, and you're right, the `2to3` tool makes it super easy to see where to make changes.

**Comment by nsheff** [comment]
@johanneskoester This should do it; `looper` can now be installed on python3. You'll have to use the version on the `dev` branch, though, which is currently `0.6.0-dev`.

**Comment by johanneskoester** [comment]
Thanks. I'll try on Monday. Have a nice weekend!

**Comment by nsheff** [comment]
@johanneskoester Can we confirm that this worked for you? I will close this issue, please re-open if not.
